name: static analysis

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  static-analysis:
    name: PHP ${{ matrix.php }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none

      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies installed with composer
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-

      - name: Update composer
        run: composer self-update

      - name: Install dependencies with composer
        run: composer update --with cycle/orm:^2.0 --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run Psalm Static Analysis
        run: |
          vendor/bin/psalm \
            --shepherd \
            --stats \
            --output-format=checkstyle \
            --php-version=${{ matrix.php }} | cs2pr --graceful-warnings --colorize
